# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github-repo:  # id of input
      description: 'Git hub repp'
      required: true
      default: 'N/A'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  repo: # id of output
    description: 'The repo name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.github-repo }}
